In [1]:
import numpy as np

**(1)** Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [5]:
meter_house=np.array([75,80,85,90,95,100,120,140,150,180])
room_house=np.array([1,2,2,2,2,3,3,4,4,4])
price_house=np.array([300000,350000,350000,350000,400000,400000,450000,500000,600000,650000])
house_all=np.array([meter_house,room_house,price_house])
print(house_all)

[[    75     80     85     90     95    100    120    140    150    180]
 [     1      2      2      2      2      3      3      4      4      4]
 [300000 350000 350000 350000 400000 400000 450000 500000 600000 650000]]


**(2)** Transpose the array you have created, so that every line can represent features of one house.

In [8]:
house_all=house_all.T
print(house_all)

[[    75      1 300000]
 [    80      2 350000]
 [    85      2 350000]
 [    90      2 350000]
 [    95      2 400000]
 [   100      3 400000]
 [   120      3 450000]
 [   140      4 500000]
 [   150      4 600000]
 [   180      4 650000]]


**(3)** Display the shape of the array and explain what it means.

In [10]:
house_all.shape #10 column, 3 row

(10, 3)

**(4)** Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [36]:
n, m = map(int, input().split()) 
array=np.ones((n,m))
print(f"shape({n}*{m}) -->")
print(f"{OnesZeros(array)}")

def OnesZeros(array):
  r,c=map(lambda x:x,array.shape)
  for i in range(r):
    for j in range(c):
      if i%2!=0 and j%2!=0:
        array[i][j]=0
  return array

6 5
shape(6*5) -->
[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]
